
package com.rapidclipse.demo.hashing.ui;

import java.beans.Beans;

import com.rapidclipse.framework.server.security.authentication.AccessibleView;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.router.RouterLink;
import com.vaadin.flow.server.InitialPageSettings;
import com.vaadin.flow.server.PageConfigurator;
import com.vaadin.flow.server.VaadinService;


/**
 *
 */
@Route("")
@AccessibleView
public class MainLayout extends VerticalLayout implements PageConfigurator
{
	/**
	 *
	 */
	public MainLayout()
	{
		super();
		
		this.initUI();
	}
	
	@Override
	public void configurePage(final InitialPageSettings settings)
	{
		settings.addLink("shortcut icon", "frontend/images/favicon.ico");
		settings.addFavIcon("icon", "frontend/images/favicon256.png", "256x256");
	}
	
	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.horizontalLayout = new HorizontalLayout();
		this.routerLink       = new RouterLink();
		this.routerLink2      = new RouterLink();
		
		this.setJustifyContentMode(FlexComponent.JustifyContentMode.CENTER);
		this.setAlignItems(FlexComponent.Alignment.CENTER);
		this.setDefaultHorizontalComponentAlignment(FlexComponent.Alignment.CENTER);
		this.routerLink.setText("Go to Hash Demo");
		if(!Beans.isDesignTime())
		{
			this.routerLink.setRoute(VaadinService.getCurrent().getRouter(), HashDemoLayout.class);
		}
		this.routerLink2.setText("Go to Common Demo");
		if(!Beans.isDesignTime())
		{
			this.routerLink2.setRoute(VaadinService.getCurrent().getRouter(), CommonLayout.class);
		}
		
		this.horizontalLayout.add(this.routerLink, this.routerLink2);
		this.horizontalLayout.setSizeUndefined();
		this.add(this.horizontalLayout);
		this.setSizeFull();
	} // </generated-code>

	// <generated-code name="variables">
	private HorizontalLayout horizontalLayout;
	private RouterLink       routerLink, routerLink2;
	// </generated-code>
	
}
